language: objective-c
osx_image: xcode8
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Tracery.xcworkspace
    - IOS_SCHEME="Tracery iOS"
    - MACOS_SCHEME="Tracery macOS"
    - IOS_SDK=iphonesimulator
    - MACOS_SDK=macosx
  matrix:
    - DESTINATION="arch=x86_64" SCHEME=$MACOS_SCHEME SDK="$MACOS_SDK" 
    # - DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.0" SCHEME=$IOS_SCHEME SDK="$IOS_SDK" 

# https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
# install: travis_wait mvn install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices
  # build the scheme + run tests
  # debug
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test -verbose | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO -verbose | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)